"""Generate the Rust catalog source from the pinned Go tree.

The Go catalog is assembled from schema files and from definitions and
registration tables declared in Go code. tools/catalog-gen/ holds a small Go
program that runs Go's own loaders in a scratch worktree of the pinned tree
and prints those declarations (never derived descriptors, edges or
revisions). The result is committed as crates/host-agent/catalog/source.json
with its provenance; the Rust crate derives the published catalog from it.

`--check` regenerates into memory and fails when the committed file differs,
so a changed pinned contract cannot reach Rust without an update (M3 E2E 2).
"""

from __future__ import annotations

import hashlib
import json
import os
import shutil
import subprocess
import tempfile
from pathlib import Path

from . import canon, runner

GEN_DIR = runner.REPO_ROOT / "tools" / "catalog-gen"
OUT_FILE = runner.REPO_ROOT / "crates" / "host-agent" / "catalog" / "source.json"


def generator_sha256() -> str:
    digest = hashlib.sha256()
    for path in sorted(GEN_DIR.glob("*.go")):
        digest.update(path.name.encode() + b"\0" + path.read_bytes() + b"\0")
    return digest.hexdigest()


def generate(src: Path) -> dict:
    lock = json.loads((runner.REPO_ROOT / "baseline" / "source-lock.json").read_text())
    head = subprocess.run(["git", "-C", str(src), "rev-parse", "HEAD", "HEAD^{tree}"],
                          check=True, capture_output=True, text=True).stdout.split()
    if head != [lock["sourceCommit"], lock["sourceTree"]]:
        raise SystemExit(f"Go source {head} is not the pinned {lock['sourceCommit']}")
    work = Path(tempfile.mkdtemp(prefix="catalog-source-"))
    tree = work / "src"
    subprocess.run(["git", "-C", str(src), "worktree", "add", "--detach", "-f", str(tree), "HEAD"],
                   check=True, capture_output=True)
    try:
        shutil.copy2(GEN_DIR / "export_tools.go", tree / "internal" / "tools" / "zz_parity_export.go")
        (tree / "cmd" / "parity-catalog-source").mkdir(parents=True)
        shutil.copy2(GEN_DIR / "main.go", tree / "cmd" / "parity-catalog-source" / "main.go")
        out = subprocess.run(["go", "run", "-trimpath", "./cmd/parity-catalog-source"], cwd=tree,
                             env={**os.environ, "CGO_ENABLED": "0"}, capture_output=True, text=True)
        if out.returncode != 0:
            raise SystemExit("catalog source generator failed: " + out.stderr[-800:])
        declarations = json.loads(out.stdout)
        for key in ("hostDefinitions", "standaloneDefinitions", "standaloneFromAll", "internalDefinitions"):
            names = [d["name"] for d in declarations[key]]
            if len(names) != len(set(names)):
                raise SystemExit(f"{key} repeats a name; sorting the export would change first-wins order")
    finally:
        subprocess.run(["git", "-C", str(src), "worktree", "remove", "--force", str(tree)], capture_output=True)
        shutil.rmtree(work, ignore_errors=True)
    return {
        "provenance": {
            "sourceCommit": lock["sourceCommit"],
            "sourceTree": lock["sourceTree"],
            "generatorSha256": generator_sha256(),
            "note": "generated by `python3 -m parity catalog-source`; do not edit",
        },
        **declarations,
    }


def render(doc: dict) -> str:
    return canon.canonical_json(doc) + "\n"


def write(src: Path) -> Path:
    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(render(generate(src)))
    return OUT_FILE


def check(src: Path) -> bool:
    fresh = render(generate(src))
    return OUT_FILE.exists() and OUT_FILE.read_text() == fresh
